balena-os/balenahup

README.md
Signed-off-by: Andrei Gherzan <andrei@resin.io>
=> README.md: Items agreed to do as next steps

Dockerfile.raspberry-pi, Dockerfile.raspberry-pi2, README.md, conf/resinhup.conf, modules/bootconf.py, modules/fingerprint.py, modules/updater.py, modules/util.py, prepare.sh, resinhup.py
@petrosagg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resinhup/8)
=> Various Fixes

conf/resinhup.conf, modules/repartitioner.py, modules/updater.py
@petrosagg
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resinhup/11)
=> Additional fixes

Dockerfile.intel-nuc, Dockerfile.raspberry-pi, Dockerfile.raspberry-pi2, Dockerfile.raspberrypi3, conf/resinhup.conf, modules/bootconf.py, modules/updater.py, modules/util.py, resinhup.py, scripts/docker-build-and-push.sh
=> Support for additional devices and implement ignored files in boot partition

conf/resinhup.conf, modules/util.py
=> Improve atomic copies and add deltaEndpoint

Dockerfile.beaglebone-black, conf/resinhup.conf, modules/bootconf.py, modules/util.py, scripts/docker-build-and-push.sh
Signed-off-by: Andrei Gherzan <andrei@resin.io>
@petrosagg @floion @telphan
=> Add support for Beaglebone Black

CHANGELOG.md, fetcher/tar.py, modules/util.py, resinhup.py
=> Implement version and custom remote

Dockerfile.beaglebone-black, Dockerfile.intel-nuc, Dockerfile.raspberry-pi, Dockerfile.raspberry-pi2, Dockerfile.raspberrypi3, conf/resinhup.conf, fetcher/dockerhub.py, fetcher/fetcher.py, fetcher/tar.py, modules/updater.py, modules/util.py, modules/util/safedircopy/dir1/ignore-dir/ignore-file, resinhup.py, run.sh, scripts/docker-build-and-push.sh
=> resinhup and dockerhub

CHANGELOG.md, conf/resinhup.conf
Connects-to: #64
Signed-off-by: Gergely Imreh <imrehg@gmail.com>
=> whitelist /etc/hostname

Dockerfile.artik5
Missed in a previous PR ( #66 )
=> artik5: update to Alpine-based image as well

upgrade-2.x.sh
Add a script that can upgrade a 2.x resinOS version to another
2.x version.
=> upgrade-2.x.sh: Add script to upgrade 2.x host OS

upgrade-1.x-to-2.x.sh
see list of overview in the PR's commit message
=> fixes to the resinhup 1->2 script based on usage

upgrade-patches/0-bootfiles
Pulling this out of #112 so that PR can refer to this file by git commit ID, instead of branch
=> adding bootfile patch that is required for the hostapps update for some versions

upgrade-1.x-to-2.x.sh
Connects-to: #99
---- Autogenerated Waffleboard Connection: Connects to #99
=> upgrade-1.x-to-2.x: static IP migration

upgrade-1.x-to-2.x.sh
In some circumstances, it seems like there are lingering processes after the data partition, which is btrfs on resinOS 1.x, is umounted. When that's the case, continuing to the next step is not desirable, as the following steps are trying to use the partition that is still in use, and will fail, resulting in a broken-modified device file system.
In these cases, manual resinHUP is needed, most likely, to update the device. So here just bail out before anything is changed in the first test. Then the device can be manually rebooted, and will come online as was before.
The second test is less likely to fail (as it's a newly created btrfs partition), but it might, so better test there too.
=> upgrade-1.x-to-2.x: check if btrfs partition was successfully umounted

upgrade-2.x.sh
Extract the version from the resinOS image that is downloaded to the device, instead of querying remote storage.
Tested on 2.0.6-2.3.0, 2.3.0->2.7.5, 2.7.5->2.7.8 updates to cover all three cases.
=> upgrade-2.x: check supervisor version based on the target image

upgrade-2.x.sh
Add support to migrate to the balena-based resinOS versions. This requires managing the docker/balena storage folder, as well as running the update a container, so that the proper update script can be run, which requires balena as well.
Tested on RPi3 and NUC for the upcoming 2.9.4 release of resinOS. Also did a number of other combinations to check that we didn't introduce any regressions (2.3.0->2.9.4, 2.3.0->2.7.8, 2.7.8->2.9.4, 2.9.4->2.9.4, 2.2.0->2.3.0)..
---- Autogenerated Waffleboard Connection: Connects to #120
=> upgrade-2.x: balena migration fixes

upgrade-2.x.sh
Properly do variable substitution.
=> upgrade-2.x: typo in script

upgrade-2.x.sh
Previous resinHUP changes have updated devices to versions that run in hostapp mode, but due to the incomplete logic of the update, the devices ended up running the new system in the "regular", old mode outside of hostapp.
Fixes #142
=> upgrade-2.x: fix balena migration for non-hostapp-mode hostapp enabled resinOS

upgrade-2.x.sh
The read command only passes the first variable starting 2.9.x, thus we cannot use it anymore to do multiple shell variable set.
Replace that call, and patch `update-resin-supervisor` which is also affected.
=> upgrade-2.x.sh: fix issues with `read` on newer resinOS versions

README.md, upgrade-ssh-1.x-to-2.x.sh, upgrade-ssh-2.x.sh
Change-type: major
Addresses: #92 
Depends-on: https://github.com/resin-io/resin-proxy/issues/195
=> running upgrade scripts over new type of SSH access

upgrade-2.x.sh
Just like it is for the x86 devices.
=> upgrade-2.x: combine supported ARM device types into a single check

upgrade-2.x.sh
Connects-to: https://github.com/resin-io/hq/issues/1344
=> upgrade-2.x: add support for TX1 updates

upgrade-2.x.sh
=> adding support for the Banana Pi M1 and the Dart board

upgrade-2.x.sh
For newer supervisor versions (7.x.y) the supervisor does not clean
up images it doesn't know of. We had taken a step before to clean
up the image after update, but we've cleaned it up too early.
The result was that the supervisor update had to repull the os
image.
Now push the cleanup to the final step when it can safely
be removed, as not needed for any other procedures.
Connects-to: #169 
---- Autogenerated Waffleboard Connection: Connects to #169
=> fix cleaning up resinOS update package

upgrade-1.x-to-2.x.sh
Seems like docker in Raspberry Pi 1 resinOS <2.6.0 cannot currently pull multilayer images correctly from Docker Hub. A workaround for those versions is to limit download concurrency to 1 with a docker
daemon flag.
This modification is applied only for updating to the affected hardware and software combinations.
Tested with Pi 1 1.26.0 -> 2.2.0+rev1 updates.
=> upgrade-1.x-to-2.x: modify docker daemon flags for in target system

upgrade-2.x.sh
For Raspberry Pi 1 devices with docker 17.03 (resinOS 2.0.0-2.5.1) are not able to currently pull multilayer images from Docker Hub, such as supervisor images.
Modify the docker command line to limit concurrent downloads, which seems to be a workaround to this issue. Do the workaround both for production and development images as needed.
=> update-2.x: workaround for RPi1 2.x devices not being able do some docker pulls

upgrade-2.x.sh
* Asus Tinker Board
* [Hummingboard](https://github.com/resin-io/hq/issues/1466)
* [Revolution Pi](https://github.com/resin-io/hq/issues/1464)
=> upgrade-2.x: Add support for new boards

upgrade-1.x-to-2.x.sh
=> upgrade-1.x-to-2.x: Fixup of supervisor updater edge case

upgrade-2.x.sh
On this specific update type (non hostapp to hostapp), on armv6 devices we observe quite often `net/http: TLS handshake timeout`, which breaks the update. Adding a retry (limited number, 10 here) should work with transient issues, as in current testing it seems transient.
Connects-to: #191 
---- Autogenerated Waffleboard Connection: Connects to #191
=> upgrade-2.x: add retries to docker pull where we expect timeouts

upgrade-2.x.sh
When an update has been interrupted, there might be data left over that would stop further updates due to out of space issues. See for more details this balena-engine issue: https://github.com/balena-os/balena-engine/issues/69
Use heuristics of lower available space and absence of hostapp containers (which are removed fine in normal update), and clean up.
Connects-to: #200 #128 
=> upgrade-2.x: Clean up inactive docker/balena folder if needed

upgrade-2.x.sh
Product issues:
* https://github.com/balena-io/balena/issues/1657
* https://github.com/balena-io/balena/issues/1658
=> upgrade-2.x: Add whitelist for imx8m-var-dart and cl-som-imx8 device types

upgrade-2.x.sh
The previous way didn't work with `overlay2` storage drivers, as the directory structure is different.
Also, for more correctness, restart the `balena-host` service after the cleanup so it would have proper information after the deletes. Without this `overlay2` cleanup doesn't work, and should be proper
for the `aufs` drivers too.
Connects-to: #205 
=> upgrade-2.x: expand on leftover data clearence after interrupted update

upgrade-1.x-to-2.x.sh, upgrade-1.x.sh, upgrade-2.x.sh
Adding 10 retries as of now. The retries back of exponentially, starting from 1s, doubling up to max 10m, this 10 retries altogether would be ~17m if all of them fail.
There are other network calls that are not made with `curl`, and thus out of the scope of this PR, but will need to be retryable in the future (mainly `hostapp-update` and `update-resin-supervisor`)
Connects-to: #202 
=> Add retries to all curl calls for more robustness

upgrade-2.x.sh
Using temp files instead of fixed file name on the host OS side fixes an issue when the update has been interrupted, but the OS hasn't been restarted before the next update attempt. In that case repeated `mkfifo` would fail with the same filename. Instead of reusing the filename, properly use a tempfile that is not clashing. Thus if the update fails, it can be safely restarted (and a new filename would be used).
=> upgrade-2.x: user tempfile for FIFO

upgrade-2.x.sh
=> upgrade-2.x: Namespaced creation temporary folder

upgrade-2.x.sh
The test previously conflated two different things: device type support
and setting a variable for device architecture that is needed in one of
the hotpatch steps. Now disentangle these:
* make the hotpatch-related architecture check automatic, and do it when   it is needed
* only do device type support check if the update version is not to a   hostapp-enabled version
* make it clearer that the device support check is needed to know how   to switch the boot partition on those OS versions (when it's not   the hostapp update hooks that do that)
* deprecate the `--assume-supported` flag, as it has no meaning now, practically
=> upgrade-2.x: redo supported device slug test

app/conf/resinhup.conf, app/fetcher/dockerhub.py, app/resinhup.py
Instead of being hard-coded into the image.
=> hup-1.x: allow updater to take a v1 Docker registry URL

upgrade-1.x.sh, upgrade-ssh-1.x.sh
=> upgrade-1.x: use the new 1.x HUP image, and allow setting the v1 registry

upgrade-1.x.sh
Relevant for exampel for v1 registry use cases
=> upgrade-1.x: also use supervisor registry if set

upgrade-1.x-to-2.x.sh
Make data partition unmount a reusable function, and add an extra umount step
for one of the partition creation, which seemed to have triggered a remount
in some old SD card cases. This umount step was verified to fix things
with the affected devices, when done in a manual update.
Connects-to: #229
=> upgrade-1.x-to-2.x: unify data partition unmounting and add preventing umount step

upgrade-1.x-to-2.x.sh
This should allow to properly cache the image information locally, and clean up any v1 registries that might have been in use before.
=> upgrade-1.x-to-2.x: also set the supervisor image name during update

upgrade-2.x.sh
This is to fix a missmatch between supervisor's expectations between
versions (older adds the incorrect empty string, while newer borks
on that value).
=> upgrade-2.x: sanitize persistent logging device config vars

upgrade-2.x.sh
=> upgrade-2.x: allow extra version format

upgrade-2.x.sh
=> typo: fix up minor exsits typo

upgrade-2.x.sh
=> logging: redirect ERROR messages to stderr (to pass back to the proxy)

upgrade-1.x-to-2.x.sh, upgrade-1.x.sh, upgrade-2.x.sh
=> replace "nohup ..." with "systemd reboot" in reboot requests

.github/CODEOWNERS
=> meta: update CODEOWNERS

upgrade-1.x-to-2.x.sh, upgrade-1.x.sh, upgrade-2.x.sh
=> silence stderr that causes "failed" HUPs

upgrade-1.x-to-2.x.sh, upgrade-1.x.sh, upgrade-2.x.sh
=> reboot: background subsequent reboot requests to exit cleanly

.github/CODEOWNERS
=> meta: add xginn8 as CODEOWNER

upgrade-2.x.sh
Depends-on: https://github.com/balena-io/balena-api/pull/2513
Depends-on: https://github.com/balena-io/balena-api/pull/2514
HQ: https://github.com/balena-io/balena/issues/1113
=> enable delta host OS upgrades

upgrade-2.x.sh
=> hostapp-images: try pulling from balena registry before DockerHub

upgrade-2.x.sh
=> TLS: reuse balenaRootCA to bypass local MitM and self-signed certs

upgrade-2.x.sh
Connects-to: https://github.com/balena-os/resinhup/issues/261
=> delta-hup: include size of delta

upgrade-2.x.sh
=> delta HUP: make size log more defensive to handle old jq + bad responses

.github/CODEOWNERS
=> codeowners: swap zubairlk and saintaardvark

upgrade-2.x.sh
=> remove DockerHub fallback for 2.x HUPs

upgrade-2.x.sh
Connects-to: https://github.com/balena-os/resinhup/issues/266
=> rename most resin to balena

.versionbot/CHANGELOG.yml
=> meta: properly generate nested changelog

upgrade-2.x.sh
=> rename: check for balenahup folders existence before symlinking

upgrade-2.x.sh
since we removed the DockerHub fallback, if there are not one target hostapps, just bail and surface the error
Connects-to: #273
=> error gracefully if number of target releases != 1

upgrade-2.x.sh
=> deltas: fix up service substitution to properly request deltas

upgrade-2.x.sh
=> private dts: enable HUP for access-restricted device types

upgrade-2.x.sh
=> legacy HUP: image -> target_image for balena registry compat

upgrade-2.x.sh
=> remove ascii_downcase function to support old host OSes

upgrade-2.x.sh
HQ: https://github.com/balena-io/balena-io/issues/2227
=> use device uuid not numeric id

upgrade-1.x-to-2.x.sh, upgrade-1.x.sh
HQ: https://github.com/balena-io/balena-io/issues/2227
=> use device uuid not numeric id in legacy scripts

upgrade-2.x.sh
=> variants: remove warning about non-prod

upgrade-2.x.sh
=> supervisor update: fix bad curl command

upgrade-2.x.sh
=> Use a named key when querying for device by uuid

upgrade-2.x.sh
=> log out from the correct REGISTRY_ENDPOINT

upgrade-2.x.sh
Connects-to: https://github.com/balena-os/balenahup/issues/296
=> registry: use provided arg for FQDN rather than local source

upgrade-2.x.sh
Recently the supervisor added a codepath that assumes no files underneath it will change during runtime.
OS update hooks can trigger a condition whereby the supervisor reboots the device during a HUP,
which in turn bricks the device.
Depends-on: https://github.com/balena-os/meta-balena/pull/1973
=> supervisor: if available, update supervisor without affecting it's state

upgrade-2.x.sh
=> meta: dts -> device types for clarity

upgrade-2.x.sh
Connects-to: https://github.com/balena-os/balenahup/issues/305
=> jetson-tx2: migrate other special-case configuration during HUP

upgrade-2.x.sh
This PR removes the sanity check in balenahup that verifies the device type.  This check examined two on-device files, in an attempt to prevent HUPs from installing OS versions incompatible with the underlying hardware.
The prompt for this change is to enable hands-off device-type changes for customers with private device types; by
removing the check, we can patch the device type in the API, and leave OS upgrades to the customer.
This has been checked on devices in staging by invoking it manually against my test devices.  In both the usual case (device type requested matches `device-type.json`) and the unusual case (device type requested does *not* match `device-type.json`), the upgrade proceeds as expected (the OS for the requested device type is fetched).
This has *not* been tested on …
=> Remove device sanity checks, as they are no longer needed

upgrade-2.x.sh
I haven't tested the entire script, but I did test the snippet for setting the SLUG, and it should be fine. I'll try to get it tested tomorrow, but it can be reviewed in the meantime (which is why is marked as draft)
See: https://www.flowdock.com/app/rulemotion/resin-devices/threads/Do15pyYgb59vcSbSGVHNBD737ki
Signed-off-by: Stevche Radevski <stevche@balena.io>
=> Make HUP fetch the device type slug from the API

upgrade-2.x.sh
=> cleanup: remove unused DEVICETYPEJSON variable

upgrade-2.x.sh
Connects-to: https://github.com/balena-os/balenahup/issues/251
=> supervisor: in case of API query failure, report the received response

upgrade-2.x.sh
=> jetson: confirm variable exists before testing it

upgrade-2.x.sh
=> supervisor-update: stop the supervisor before PATCHing the new target

upgrade-2.x.sh
Connects-to: https://github.com/balena-os/balenahup/issues/333
=> ESR: properly grab the meta-balena version from /etc/os-release

upgrade-2.x.sh
Connects-to: https://github.com/balena-os/balenahup/issues/338
=> reporting: retry failure reporting until successful

upgrade-2.x.sh
Maintain compatibility with resin namespaces for now.
=> Rename resin-supervisor to balena-supervisor

upgrade-ssh-2.x.sh
=> 2.x: remove resin remnants from ssh script

upgrade-2.x.sh
Resolves: https://github.com/balena-os/balenahup/issues/358
=> upgrade-2.x: Catch failure when dumping sv update logs

upgrade-2.x.sh
See: https://jel.ly.fish/51fc3ffe-33de-40c4-8982-abeb89717d08
=> Temporarily disable upgrades to 2.83.10+rev1 for Pi4

upgrade-2.x.sh
=> Deprecate VARIANT in os-release file

upgrade-2.x.sh
See: https://jel.ly.fish/improvement-combine-os-variants-0d96399a-660b-4d38-adca-f661378cb86e
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>
=> upgrade-2.x: Add support for upgrading to unified OS releases

upgrade-2.x.sh
REC files are generated by fsck and fills up
the boot partition quickly which causes failures
in updates. Clean this up before proceeding with
the update.
Signed-off-by: jaomaloy <jao.maloy@balena.io>
=> upgrade-2.x: Remove REC files before updating

.github/workflows/flowzone.yml
=> flowzone: add workflow

upgrade-2.x.sh
=> upgrade-2.x.sh: Adapt to support major balenaOS version upgrades

upgrade-2.x.sh
When a reboot is requested take into account that user applications might be in critical sections and might have requested for the reboot to wait.
=> upgrade-2.x: perform a safe reboot taking locks into account

upgrade-2.x.sh
This will allow to eventually surface the HUP logs to the dashboard.
=> upgrade-2.x.sh: log to journal when available
