balena-os/balenahup

conf/resinhup.conf
modules/updater.py
modules/util.py
resinhup.py

Verify config.json and add all the missing info there based on running flag
Based on --staging argument (default to production when not present),
config.json will be check for all the required attributes and fix accordingly.
Signed-off-by: Andrei Gherzan <andrei@resin.io>
CC @petrosagg @telphan @floion
PR for #3
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/resin-os/resinhup/4)

Verify config.json and add all the missing info

---

conf/resinhup.conf

This file might have been already change by supervisor updates.
Signed-off-by: Andrei Gherzan <andrei@resin.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/resin-os/resinhup/13)

resinhup.conf: Keep /etc/supervisor.conf over updates

---

scripts/docker-build-and-push.sh

The new option is -r, or --registry
Also fix a bug that manifested itself if two images with the same
name, but different tags existed.

docker-build-and-push: add configurable registry

---

scripts/docker-build-and-push.sh

Make the help message look a bit more like a unix manpage.

docker-build-and-push.sh: help message tweaks

---

fetcher/tar.py

The `update` object will not exists on this place. Mybe we would find other bugs with a pylint check.

Bugfix: 'update' not exists on this place.

---

CHANGELOG.md
conf/resinhup.conf

This should allow us to do resinhup upgrades on staging devices.

Whitelist etc/openvpn/resin.conf fingerprint

---

CHANGELOG.md
modules/updater.py

Trying to copy with wrong syntax (to a directory, instead of a file),
which breaks update process.
Commit-type: patch
Signed-off-by: Gergely Imreh <imrehg@gmail.com>

legacy-config: fix bug when migrating config.json

---

upgrade-2.x.sh
upgrade-ssh-2.x.sh

This includes:
* supervisor update automatically to the target resinOS version's shipped supervisor or as defined on the command line with `--supervisor-versions`
* add `resin-device-progress` on devices that shipped with broken version (above 2.6.0 and below 2.3.0, those two versions are good)
* update x86 tools download path
* restart supervisor if the script exits with an error
* other small fixes for shellcheck and scripting
Replaces https://github.com/resin-os/resinhup/pull/84 which was on an external branch.

further improvements to the 2.x->2.x updater

---

upgrade-2.x.sh
upgrade-ssh-2.x.sh

The set of changes in this PR:
* The logging function in this file was already able to handle logging to a file (eg. for when the script is invoked through the proxy). Add the relevant setup section and command line flags to actually make use of it.
* being able to use staging resinOS docker hub
* switching order of supervisor update with rootfs switch for bringing upgrade changes closer to each other (and be reversible if the supervisor update fails)
* adding logic to handle the root of Beaglebone and NUC devices properly
* add better logging that saves all logs into the file (including standard output and errors)
* checking if image:tag exists in registry (docker hub) and bail out if not
* remove vulnerable `resin-sample` from the device if present on update #93 
* fix logic of getting …

upgrade-2.x: changes in preparation to self-service hup

---

upgrade-1.x-to-2.x.sh
upgrade-ssh-1.x-to-2.x.sh

* Exit properly when switching root partition
* Source profile to get proper path information
* Enable loging (to /tmp/ as for 1.x->2.x the only filesystem  that does not
change in the process)
* Allow pulling from the staging resinOS Docker HUB repository
* Add script to call the updater through ssh (optional, for manual updates)
* Increase minimum hostos starting version for BB, so that we avoid the eMMC bug
* Bail out better if the resinos image download fails (instead of silently dying)
* Better logging on the device
* Checking if image:tag exists in registry (docker hub) and bail out if not
* Fix start-resin-supervisor for versions that have broken logic
* Log error properly when resin-data backup fails (e.g. if backup larger than available space to back up)
* For releases that come …

ugrade-1.x-to-2.x: changes to go into the self-service HUP

---

upgrade-2.x.sh

These versions had update-resin-supervisor that couldn't properly query the API for an update.

upgrade-2.x: update-resin-supervisor polyfill for 2.0.8-2.7.0 versions

---

upgrade-1.x-to-2.x.sh

Define a top version where to apply the supervisor bootstrap fix, now that the fix was merged and released in meta-resin 2.7.3.
Connects-to: https://github.com/resin-os/meta-resin/pull/877
(tested with update 1.30.1->2.4.2 which needs fix, and 1.26.0->2.7.5 which does not need fix)

upgrade-1.x-to-2.x: supervisor bootstrap add highest target version

---

upgrade-1.x-to-2.x.sh

Noticed, that the existing script, generating the ext4 partitions, using the default parameters results in somewhat less space on the 2.x device's root partition. This is fixed by applying the same setting as it is done creating the partitions on 2.x.
Previous updater script, updating from 1.26.0->2.3.0:
Trimmed output of `fdisk -l /dev/mmcblk0`:
```
/dev/mmcblk0p3       729088  1368063   638976  312M 83 Linux
```
Trimmed output of `df -h`:
```
/dev/mmcblk0p3                  295M  226M   49M  83% /
```
The new updater script with these changes, trimmed output of `df -h`:
```
/dev/mmcblk0p3                  300M  226M   54M  81% /
```

upgrade-1.x-to-2.x: unify ext4 file system creation as it is done on 2.x

---

upgrade-1.x-to-2.x.sh
upgrade-2.x.sh

Some parts had mixed tabs/4-spaces indentations, which made the script difficult to use manually. Unify on 4-spaces.

upgrade-scripts: fix indentations

---

upgrade-1.x-to-2.x.sh
upgrade-2.x.sh
upgrade-ssh-1.x-to-2.x.sh
upgrade-ssh-2.x.sh

Introducing a couple of new flags:
* --resinos-registry: the docker registry to pull from, defaults to Docker Hub
* --resinos-repo: the docker repository in that registry, defaults to resin/resinos
* --resinos-tag: overriding the automatic inference of the resinOS image tag
* --force-slug: override automatic slug detection of the script
It also modifies the behaviour of the --staging flag. That flag was only used to infer the resinos repo, so it now acts as if --resinos-repo resin/resinos-staging was set.
Change unrecognized options to warnings for the update scripts. This is to enable in the same time using these new flags on the resinOS 2.x->2.x updates, while not needing to implement them in the 1.x->2.x scripts, which are in maintenance mode.

upgrade-2.x: new flags to pull resinOS from custom repository

---

upgrade-2.x.sh

Incorporated feedback on typos of help text.
Made --staging flag not just set the --resinos-repo flag, but also override that flag, so the result does not depend on the order in which the two flags might have been supplied by default.

upgrade-2.x: fixing up help text, making --staging more safe

---

upgrade-2.x.sh

Some supervisor versions are not great at database migration, and after HUP might not start up properly. Remove the database for the affected versions' updates as a workaround. Fixed such issues in supervisor v6.5.7 and v6.5.9.

upgrade-2.x: remove supervisor database after upgrade for some versions

---

upgrade-2.x.sh

Only support versions >=2.7.4. Tested with 2.7.4+rev1->2.7.4+rev1 and 2.7.4+rev1->2.8.1+rev2 updates
Connects-to: #138 
---- Autogenerated Waffleboard Connection: Connects to #138

upgrade-2.x: add support for Jetson TX2 and related devices

---

upgrade-2.x.sh

Applicable for resinOS >=2.4.1, as the storage driver has changed with that version.
Connects-to: #127 
---- Autogenerated Waffleboard Connection: Connects to #127

upgrade-2.x: add support for ts4900 device type

---

upgrade-2.x.sh

Should work starting from resinOS 2.9.2+rev1 on QEMU, though might want to limit in practice to 2.9.3+rev1 and upwards (as 2.9.2 is missing `resin-device-progress`)

upgrade-2.x: add QEMU support for resinHUP scripts

---

upgrade-2.x.sh

The update should work target resinOS versions >=2.9.7, and production versions should be supported for the starting version.
Extra `device-type.json` check is added, as on older resinOS versions that file was not shipped in the boot partition by default.

upgrade-2.x: add support for Intel Edison updates on resinOS 2.x

---

upgrade-2.x.sh
upgrade-ssh-2.x.sh

The flag let resinHUP to stop user application before proceeding to the actual update. This can be useful in case for example running manual host OS updates on devices whose application is known to interfere in some way.
Tested on a number of upgrades from & to 2.3.0 / 2.7.8 / 2.9.7 on a Raspberry Pi.

upgrade-2.x: add flag to stop user application before updates

---

upgrade-1.x-to-2.x.sh
upgrade-2.x.sh

Adding locking functionality to the update scripts based on this method: https://stackoverflow.com/a/1985512
Locking at the very beginning of the update, and when the updater exits, the lock should be released.
Connects-to: #101 
---- Autogenerated Waffleboard Connection: Connects to #101

upgrade scripts: use lockfile to prevent multiple updates running

---

upgrade-2.x.sh

That container removal step is unnecessary for most supervisor updates,
and in fact it will prevent a successful update on resinOS 2.12.0,
due to a balena issue.
Solution is not to do that step unless it's necessary.

upgrade_2.x: change when to remove containers for supervisor updates

---

upgrade-1.x.sh
upgrade-ssh-1.x-to-2.x.sh
upgrade-ssh-1.x.sh

Also modified the scripts to use the new connection method to the devices, just like the other updater scripts do.
The output log name has changed as well, and updated the 1x->2x updater script's log output filename in the same pattern.

upgrade-1.x and upgrade-ssh-1.x: moving/adapting scripts from meta-resin

---

upgrade-2.x.sh

Tested updating from 2.0.4, 2.0.8, 2.2.0 to the latest stable 2.2.0 and the upcoming 2.12.3 version.
HQ: https://github.com/resin-io/hq/issues/1265

upgrade-2.x: add support for the Artik710 device type

---

upgrade-1.x-to-2.x.sh
upgrade-1.x.sh
upgrade-2.x.sh

* Adding lockfile support to 1.x updater
* Move internal locking point within the scripts, so it happens after
command line parsing, otherwise user cannot view the help of the script
* Rename lockfile, as was assumed that `.lock` extension is automatically
applied, but that's a wrong assumption

upgrade-1.x/1.x-to-2.x/2.x: lockfile improvements

---

upgrade-2.x.sh

Treating that update attempt as an error is likely not really helpful. Since the resin.io dashboard does not enable updating `.dev` devices anyways, but in support we do some updates for dev device updates (which is then intentional and cleared with the users), if we just warn in the logs should be enough for the time being, until a better story is developed with .dev updates in general.

upgrade-2.x: upgrading a `.dev` device switched from error to warning

---

upgrade-2.x.sh
upgrade-ssh-2.x.sh

The flag skips SLUG check for device support, and allows update, but only for target versions that are using the update hooks, thus this updater does not need to explicitly know how to switch the root partition.

upgrade-2.x: add new flag to assume supported device

---

upgrade-1.x-to-2.x.sh
upgrade-2.x.sh

$SECONDS is not resilient to OS time changes (eg. time synchroniziation) happening during the run of the script, which can cause issues with the way timeout was checked in the scripts.
Switch to iteration count with known sleep time, which is robust against to underlying time changes.
Tested with updates on a VirtualBox NUC:
* 1.26.0->2.2.0
* 2.2.0->2.7.8->2.9.7
* 2.2.0->2.7.8 (legacy update method)->2.9.7
These updates exercise all the modified code paths.

upgrade-1.x-to-2.x/-2.x: replace $SECONDS with iteration counter

---

upgrade-2.x.sh

On newer resinOS versions the supervisor does not clean up automatically (from 2.12.0 onwards), thus the updater needs to do that if the userspace docker engine was used.

upgrade-2.x: clean up after in-container resinOS updates

---

upgrade-2.x.sh

Enabling the following device types
* `fincm3`
* `odroid-c1`
* `odroid-xu4` (should be only for starting version >=2.9.7)
* `orangepi-plus2`
This is a quick way to add support without refactoring, which is needed to support any hostapp-enabled system by default.
Tested the first three, the last one should be working as long as `hostapp-update` works, and that's part of the release testing.

adding support for more devices

---

upgrade-1.x-to-2.x.sh

This might help with some SD cards that are slow to write to disk. Might not, if the card's faulty or tells the system that things are written to disk, but actually not. Still should be a general improvement upon the previous state, even if `sync` was already called by the code later, just before reboot.

upgrade-1.x-to-2.x: force dd to physically write stuff to disk before finishing

---

upgrade-1.x-to-2.x.sh

upgrade-1.x-to-2.x: when switching root partitions, run check after writing

---

upgrade-2.x.sh

Previous fix freaks out as the circumstances have changed and some files are no longer shipped.

update-2.x: resinOS >=2.13.1 does not have timesyncd so no need to fix

---

upgrade-2.x.sh

The versions affected are `[2.0.8, 2.7.0)`, and 2.0.8 was previously excluded from the range (effectively giving `(2.0.8, 2.7.0)`. The new check is then evaulated as 2.0.7 < version < 2.7.0, which is the correct range.
Signed-off-by: Gergely Imreh <imrehg@gmail.com>

upgrade-2.x: update OS version check for update-resin-supervisor fix

---

upgrade-2.x.sh

Signed-off-by: Gergely Imreh <gergely@resin.io>

upgrade-2.x: add orbitty-tx2 to supported device types

---

upgrade-2.x.sh

For an ongoing issue with ARMv6 devices downloading multilayer images from Docker HUB, we need to switch docker to not run parallel downloads. The option used for that is only available for resinOS versions 2.0.7+ and versions below 2.5.0 are affeccted. Thus only cover those versions with the immediate fix, which is mainly needed for the supervisor update only.
For `raspberry-pi` device type (the only one affected) on resinOS versions <2.0.7, the supervisor update will not succeed in the pull step, but the device will self-recover ~15 minutes after reboot, when repulling
the supervisor by the regular scheduled supervisor updater. This inconvenience is a tradeoff, as we don't know any other workaround for this issue yet.
Signed-off-by: Gergely Imreh <gergely@resin.io>

upgrade-2.x: only switch docker to single download where available

---

upgrade-1.x-to-2.x.sh

Previously we got it from S3, but actually we can get it from the new OS, similarly to 2.x-2.x updates.
Still need some code cleanup, but it should now work with the new supervisor releases for the new logging system.

upgrade-1.x-to-2.x: get the supervisor version from the new root

---

app/conf/resinhup.conf

The `resinhup.conf` configuration file contains `mixpanelToken`
variables that seem to be unused by the code.
After digging around a bit, `app/modules/updater.py` mentions
`mixpanelToken`, but in a function that converts a `resin.conf` file
that contains `MIXPANEL_TOKEN`, into `config.json`, so I believe this is
a safe deletion.

resinhup.conf: Remove unused mixpanelToken variable

---

upgrade-2.x.sh

Balena migration requires moving the existing docker folder (used by docker-host) to the new balena folder. In some cases that migration wasn't done properly, as somehow there was a balena folder already, and the previous logic didn't clear that up. This resulted in inability of update as the partition runs out of space.
Example is 2.7.5->2.7.8->anything above 2.9.0. The second step did not succeed.
The modified cleanup handles handles migration more robustly.
Connects-to: #193
---- Autogenerated Waffleboard Connection: Connects to #193

upgrade-2.x: Fix balena migration

---

upgrade-2.x.sh

Previously sometimes it was left there for certain updates, such as 2.7.8->2.13.6 as tested.
Connects-to: #194 
---- Autogenerated Waffleboard Connection: Connects to #194

upgrade-2.x: Properly remove update image when needed

---

upgrade-1.x.sh

We have some resinOS 1.x versions that have backported, logstream enabled supervisors. The updater checks the `VERSION` file online to see what supervisor version to update to. Previously the version
in that file was `a.b.c-shortsha`, and we've thrown away anything after the dash. In this case we have to communicate that it's a logstream supervisor, and the cleanest is storing `a.b.c-logstream` in that file. The updater with this change turns that version into a supervisor tag, `va.b.c_logstream` ultimately, while backwards compatible with non-logstream versions online (as long as they are available).

upgrade-1.x: Properly handle updates to logstream 1.x versions

---

upgrade-2.x.sh

When stopping the supervisor service and container, also remove the container, so next time when it starts up it will be recreated.
This might be important for updates, as there could be a race condition, the new supervisor starting up on the old system, and if the container is just stopped, when rebooting the restart will carry over strange states.
This possibly fixes issues when a lockfile is detected by the supervisor, but it might be just from an earlier run of supervisor that was stopped at the right time. If no container, no data is carried over.
Flowdock: https://www.flowdock.com/app/rulemotion/r-supervisor/threads/rzXzsmyWhiAY8ZhGRR3xAYwmeFe

upgrade-2.x: Remove supervisor container not just stop

---

upgrade-1.x-to-2.x.sh

In the partition copy step, first we switch partitions to read-only, then do a `dd` copy between them. Noticed that some SD cards/some devices the comparison afterwards fails, but if running the same `dd ...` line again, then succeeds.
The current theory is that the `dd` starts too soon before all data was written to disk after switching to read-only. Experimentally I don't hit the integrity check fail again (tested on multiple devices that exhibited that error).
The symptom-tracking issue is #186.
Connects-to: #186

upgrade-1.x-to-2.x: Add sync after going read-only for safety

---

upgrade-1.x-to-2.x.sh

Previously some `etc/{docker,dropbear}` folders were created on the state partition but the files intended to go there were not copied to the right place. Fix the path. Likely this is not fatal, as we've done 1000s of updates so far with this in place, but the fix will make the migration correct as intended.

upgrade-1.x-to-2.x: Fix incorrect migration to the state partition

---

upgrade-1.x-to-2.x.sh

Previously under some circumstances the pull would fail, leaving
the whole update in limbo. The failure seemed to have been
reproducable for Intel NUC updates, where it whould go:
```
Pulling repository docker.io/resin/resinos
Error while pulling image: Get https://index.docker.io/v1/repositories/resin/resinos/images: dial tcp: lookup index.docker.io on 127.0.0.2:53: server misbehaving
```
With this retry, the pull is more robust.

upgrade-1x-to-2x: add retries to the docker pull step

---

upgrade-1.x-to-2.x.sh

There are changes in 2 commits in this PR:
* before creating an `ext4` file system on any partition that had `ext4` already before, erase the partition, otherwise it might run into a `ext2fs_update_bb_inode: Illegal triply indirect block found while setting bad block inode` issue (happens very rarely, but happened in support a couple of times recently)
* add sync to any `cp` step to make sure the data is properly written to disk
* do not unmount the boot partition, it doesn't seem to be necessary, and can cause issues if there's any error during the time that it is unmounted.
More comments in each commit's message.

1.x->2.x update improvements

---

upgrade-1.x-to-2.x.sh
upgrade-2.x.sh

Also move the API keys from query parameter to header, to keep it out of our logs.

upgrade 1x2x/2x: bump API calls to the latest API version

---

upgrade-2.x.sh

The previous timeout was 0.2s * 150=30s, which is got hit by some otherwise normally working devices, that might be a) slower than usual, b) the user application might be taking too much of the resources. Increase this x10, 0.2s * 1500=300s=5min, which is still quite short, and definitely shorter than if the user needs to ask support and retry because of "spurious" timeouts. Valid errors should be still caught quite quickly.

upgrade-2.x: increase timeout values during update to 5 minutes

---

upgrade-2.x.sh
upgrade-ssh-2.x.sh

Previously we might have logged when there wasn't any logfile setup, for example if any of the argument parsing was throwing an error, and on the 2.x updater there wasn't any way to directly know what the error was, just that the update didn't start.
Moving the logfile setup before any logging takes place eliminates this issue. The flag was also only really used in manual HUP runs (no way to use in self-serve updates), and it's more relevant to 1.x updates than anything since.

Remove "--nolog" flag from 2.x updater, and always set up logfile

---

upgrade-2.x.sh

We want to allow such updates in the future.

upgrade-2.x: Do not error out when getting a .dev device version

---

upgrade-2.x.sh

fix: backfill missing image variable for legacy upgrades

---

upgrade-2.x.sh

since the variable is not set as an integer, we are simply appending to
the string rather than incrementing the value:
```
[000000009][WARNING]Couldn't pull docker image, was try #0...
[000000019][WARNING]Couldn't pull docker image, was try #01...
```

non-hostapp: fix up retry count non-integer issue

---

upgrade-2.x.sh

As sorted in https://github.com/balena-os/meta-balena/pull/2013, we
missed some files in the hooks blacklist that cause devices to brick in
the field. until all jetson-tx2 devices are past balenaOS 2.58.3, we'll
need to sort this as part of the HUP process.

jetson-tx2: fix for accidental overwrite of extlinux.conf

---

upgrade-2.x.sh

currently there are occasions when a supervisor upgrade does not
complete before the HUP reboots a device. this causes confusion when the
supervisor eventually does update 15 minutes after boot.
Connects-to: https://github.com/balena-os/balenahup/issues/300

supervisor: wait for upgrade unit to complete

---

upgrade-2.x.sh

In order to detect issues with deltas and work around them with a
regular pull, we need `hostapp-update` to fail and propagate that back
to our caller. By splitting out these post-update steps into a different
function, we can `&&` them together and restore the previous behavior.

post-update-workarounds: allow `hostapp-update` to fail properly

---

.github/CODEOWNERS

meta: remove legacy codeowners

---

upgrade-2.x.sh

since older OSes get a sideloaded balenaOS hostapp, it is untagged in
the local image store. when we crack that image open to find our new
target supervisor, we have to contact the upstream registry and retag
our local image with the registry reference. in order to do that, we
must remain logged in.
Connects-to: #331

private DTs: do not log out from the registry until cleanup

---

upgrade-2.x.sh

Connects-to: https://github.com/balena-os/balenahup/issues/338

logging: retry reporting failures every minute for an hour

---

upgrade-2.x.sh

W/o this, HUP is retrieving invalidated releases as well, blocks HUPing to any version for which we also have an invalidated release (on top of the obvious issues that HUPing to an invalidated release might have)
I don't know how to test that, so plz someone either do it for me or guide me on how to do it before approving.
See: https://www.flowdock.com/app/rulemotion/resin-tech/threads/Q6G8ZOdl8tbn1uLErpDe4_0bwBD
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

Filter out invalidated hostApp releases

---

upgrade-2.x.sh

Rather than attempting to print logs after a failed
supervisor update just default to piping the logs during
the systemd-run command and print the warning afterwards
if required.
Resolves: https://github.com/balena-os/balenahup/issues/352

upgrade-2.x.sh: Prevent supervisor update from halting HUP

---

upgrade-2.x.sh

The --pipe flag is not supported in older versions of systemd like
those running on balenaOS 2.31.2+rev1.
Restore the old behaviour of runnning a separate systemctl status
command after the upgrade transient service has completed or failed.
Reverts: https://github.com/balena-os/balenahup/pull/353
Resolves: https://github.com/balena-os/balenahup/issues/355

upgrade-2.x.sh: Remove unsupported flag from supervisor upgrade

---

upgrade-2.x.sh

A mistyped path in the hostapp-update hooks in meta-balena caused the
extlinux.conf file to not be persisted across HUP, causing variables set
in the config to be reset by the supervisor, triggering untimely reboots
during upgrades.
A fix has been made to meta-balena [0] to properly persist the
configuration across a HUP, but this will require an OS upgrade to take
effect.
The supervisor has a similar fix in place to prevent reboots when
healthcheck breadcrumbs are present, but this requires a new supervisor
release.
To cover devices that are running older supervisor releases on older OS
versions, extend the version check to apply the Jetson fix to affected
OS versions.
[0] https://github.com/balena-os/meta-balena/commit/096024808224aea2100e2a2a1f95ef75e23493ef …

upgrade-2.x: apply jetson fix to OS < v2.84.7

---

upgrade-2.x.sh

Starting with BalenaOS v2.85.9 the u-boot bootcount limit
has been increased to 3. Let's apply this fix previous
jetson-tx2 releases, like 2.73 or 2.82.
Signed-off-by: Alexandru Costache <alexandru@balena.io>

Backport increased os_bc_limit to existing releases

---

upgrade-2.x.sh

BalenaOS has renamed SUPERVISOR_TAG for SUPERVISOR_VERSION in
supervisor.conf.
Signed-off-by: Alex Gonzalez <alexg@balena.io>

upgrade-2.x.sh: Use SUPERVISOR_VERSION for version check

---

upgrade-2.x.sh

This has been removed with the aufs to overlay2 transition.
Needs to check that HUPs between an aufs based OS and an overlay2 based one stills spaws the docker daemon with the correct storage engine.
Resolves: https://github.com/balena-os/balenahup/issues/372

Stop reading the storage driver from the boot partition

---

upgrade-2.x.sh

We need this for newer balenaOS devices which
we plan to release, for example the Jetson Orin
Nano wich will have the first production image on
balenaOS 3.x, as well as for the devices which will be updated
in the future to 3.x and newer

upgrade-2.x: Allow upgrading from balenaOS v3.x

---

upgrade-2.x.sh

* Allow draft updates
* Use `raw_version` for image location fetch and fallback to `version` label
* Improve error reporting to cloud with the use of a signal trap handler
Relates-to: https://github.com/balena-os/meta-balena/issues/3257

upgrade-2.x failure reporting

---

upgrade-2.x.sh

Atm given a draft OS release 3.2.1-2345, users would be able to HUP to it via both
* `device os-update 3.2.1-2345`, in which case the script finds the version via the `raw_version` field
* and `device os-update 3.2.1`, in which case the script find the version via the `release_tag`
After this, HUPing to draft-OS releases will only work using the `raw_version` which removes the ambiguity and block users from accidentally HUPing to a draft release (eg they misstype the patch version or on purpose try to increase it to check whether a new version is out).
Partially reverts commit ce70f31ba4bda575fef4fecf0e50ac1eb3a1d8cf.
See: https://balena.fibery.io/Work/Improvement/Remove-hostApp-version-release-tag-dependency-from-API-1412

upgrade-2.x: Block draft version upgrades using the release_tag version

---

upgrade-2.x.sh

See: https://balena.fibery.io/Work/Project/Use-the-release-semver-fields-along-with-release_tags-across-all-our-components-404

Upgrade-2.x.sh: Comment why we still need to use the release_tags

---

upgrade-2.x.sh

This avoids any issues with partitions being mislabeled leading to a bricked device.
See: https://balena.fibery.io/Inputs/Pattern/Generic-x86_64-GPT-with-sw-RAID1-fails-HUP-4508
See: https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Several-self-hosted-GitHub-runners-unresponsive-after-failed-HUP-23

Check that active and inactive partitions differ

---

upgrade-2.x.sh

On some device types, the df command will return
a part UUID instead of the root device name.
This fixes the expected behaviour on Generic AARCH64 devices.
See: https://github.com/balena-os/balenahup/pull/405
See: https://balena.fibery.io/Inputs/Pattern/Generic-x86_64-GPT-with-sw-RAID1-fails-HUP-4508
See: https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/Several-self-hosted-GitHub-runners-unresponsive-after-failed-HUP-23

Resolve part UUID links returned by df

---

upgrade-takeover.sh

This script is equivalent to `upgrade-2.x.sh`, but for takeover based HUP. This script is derived from `upgrade-2.x.sh`, but removes unnecessary functionality. It also aims to be a model for a script implementation but avoiding gratuitous changes to the `upgrade-2.x.sh` original.
I am looking for higher level comments on the approach at this point. I have added some questions in the code. Don't mind the individual commits. I will squash them later.

Add takeover based HUP script

---

upgrade-takeover.sh

* Ensure work dir cleaned up
* Update for revised takeover binary options
* Use latest release

Fixes to takeover upgrade script in preparation for release
